### ISSUE TITLE
certificate verification fails

### ISSUE THREAD

**Issue by sigmoidal** [mkouhei/openssh-ldap-pubkey#7]
I am trying to use the utility, but I keep getting:

```
2017/12/14 02:02:27 LDAP Result Code 200 "Network Error": x509: certificate signed by unknown authority
```

It only works if I use the `-skip` switch, but I guess that means it doesn't really verify the certificate.
I use Let's Encrypt certs and provide them via /etc/nslcd.conf

Am I doing something wrong?

It would be nice if this could be fixed. thanks.

**Comment by sblaisot** [comment]
This issue has been fixed with #19
